[core]
port = "29800"
slack_url = "SLACK_URL"
qps = QPS
max_delay_duration = MAX_DELAY

[[tags]]
tag = "TAG"
channel = "CHANNEL"
username = "slackboard"
icon_emoji = ":clipboard:"
parse = "full"

[log]
access_log = "stdout"
error_log = "stderr"
level = "debug"
